Object.registerClass(	"fcFrutiConnect",	FrutiConnect		);
Object.registerClass(	"butText",		but.TextBasic		);
Object.registerClass(	"basicIconList",	cp.IconListBasic	);

Object.registerClass(	"fcRoom",		fc.Room			);
Object.registerClass(	"fcMenu",		fc.Menu			);
Object.registerClass(	"fcMenuSlot",		fc.menu.Slot		);
Object.registerClass(	"fcSlGame",		fc.slot.Game		);
Object.registerClass(	"fcSlChat",		fc.slot.Chat		);
Object.registerClass(	"fcSlList",		fc.slot.List		);
Object.registerClass(	"fcUserSlot",		fc.UserSlot		);
Object.registerClass(	"fcError",		fc.Error		);
Object.registerClass(	"fcBasicButton",	fc.BasicButton		);
Object.registerClass(	"fcPanCreateGame",	fc.pan.CreateGame	);
Object.registerClass(	"fcPanWaitGame",	fc.pan.WaitGame		);
Object.registerClass(	"fcPanChat",		fc.pan.Chat		);
Object.registerClass(	"fcPanUserList",	fc.pan.UserList		);
Object.registerClass(	"fcPanKOHWaitList",	fc.pan.KOHWaitList	);

Object.registerClass(	"cpMultiTextField",	cp.MultiTextField	);
Object.registerClass(	"cpDocument",		cp.Document		);
Object.registerClass(	"sbRound",		sb.Round		);

Object.registerClass(	"dePage",		de.Page			);
Object.registerClass(	"deInput",		de.Input		);
Object.registerClass(	"deText",		de.Text			);
Object.registerClass(	"deUrl",		de.Url			);
Object.registerClass(	"deRadio",		de.Radio		);
Object.registerClass(	"deCheckBox",		de.CheckBox		);
Object.registerClass(	"deComboBox",		de.ComboBox		);
Object.registerClass(	"deStyledText",		de.StyledText		);