all: project

debug:
	haxe fr.hxml -debug
	haxe de.hxml -debug
	haxe en.hxml -debug
	haxe es.hxml -debug
	
project:
	haxe fr.hxml -D prod
	haxe de.hxml -D prod
	haxe en.hxml -D prod
	haxe es.hxml -D prod
